package com.pat.portfolio.core.constants

data object ExternalUrls {
    // Programming languages
    const val ANGULAR_URL = "https://angular.dev/"
    const val BICEP_URL = "https://learn.microsoft.com/azure/azure-resource-manager/bicep/"
    const val CSHARP_URL = "https://dotnet.microsoft.com/languages/csharp"
    const val KOTLIN_URL = "https://kotlinlang.org/"
    const val KOBWEB_URL = "https://kobweb.varabyte.com/"
    const val COMPOSE_HTML_URL = "https://github.com/JetBrains/compose-multiplatform/#compose-html"
    const val DART_URL = "https://dart.dev/"
    const val DOTNET_URL = "https://dotnet.microsoft.com/"
    const val FLUTTER_URL = "https://flutter.dev/"
    const val FRAMER_URL = "https://www.framer.com/motion/"
    const val GREENSOCK_URL = "https://gsap.com/"
    const val CSS_URL = "https://developer.mozilla.org/en-US/docs/Web/CSS"
    const val HTML_URL = "https://developer.mozilla.org/en-US/docs/Web/HTML"
    const val JAVASCRIPT_URL = "https://developer.mozilla.org/en-US/docs/Web/JavaScript"
    const val JQUERY_URL = "https://jquery.com/"
    const val JSON_URL = "https://www.json.org/"
    const val LIQUID_URL =
        "https://learn.microsoft.com/azure/logic-apps/logic-apps-enterprise-integration-liquid-transform/"
    const val NEXT_JS_URL = "https://nextjs.org/"
    const val NODEJS_URL = "https://nodejs.org/"
    const val PHP_URL = "https://www.php.net/"
    const val POWERSHELL_URL = "https://learn.microsoft.com/powershell/"
    const val REACT_URL = "https://react.dev/"
    const val REDUX_URL = "https://redux.js.org/"
    const val SQL_URL = "https://www.w3schools.com/sql/"
    const val TYPESCRIPT_URL = "https://www.typescriptlang.org/"
    const val XML_URL = "https://developer.mozilla.org/docs/Web/XML"
    const val XSLT_URL = "https://developer.mozilla.org/docs/Web/XSLT"
    const val YAML_URL = "https://yaml.org/"

    // Tools
    const val AFFINITY_DESIGNER_URL = "https://affinity.serif.com/designer/"
    const val ANDROID_STUDIO_URL = "https://developer.android.com/studio"
    const val AZ_CLI_URL = "https://learn.microsoft.com/cli/azure/"
    const val AZURE_DEVOPS_URL = "https://azure.microsoft.com/products/devops/"
    const val AZURE_POWERSHELL_URL = "https://learn.microsoft.com/powershell/azure/"
    const val AZURE_URL = "https://azure.microsoft.com/"
    const val BIZTALK_URL = "https://learn.microsoft.com/biztalk/"
    const val CONFLUENCE_URL = "https://www.atlassian.com/software/confluence"
    const val COSMOSDB_URL = "https://azure.microsoft.com/products/cosmos-db/"
    const val FHIR_URL = "https://www.hl7.org/fhir/"
    const val FIGMA_URL = "https://www.figma.com/"
    const val GIT_URL = "https://git-scm.com/"
    const val GOOGLE_ADMOB_URL = "https://admob.google.com/home/"
    const val GOOGLE_CLOUD_URL = "https://cloud.google.com/"
    const val INTELLIJ_URL = "https://www.jetbrains.com/idea/"
    const val MARIADB_URL = "https://mariadb.org/"
    const val MATRIX_URL = "https://matrix.org/"
    const val MSSQL_URL = "https://www.microsoft.com/sql-server"
    const val MS_SUITE_URL = "https://www.microsoft.com/Microsoft-365"
    const val NOTION_URL = "https://www.notion.so/"
    const val VERCEL_URL = "https://vercel.com/"
    const val VS_CODE_URL = "https://code.visualstudio.com/"
    const val VS_URL = "https://visualstudio.microsoft.com/"

    // Contact urls
    const val LINKEDIN_CONTACT_URL = "https://www.linkedin.com/in/patrick-hettich/"
    const val GITHUB_CONTACT_URL = "https://github.com/Pat992/"

    // API urls
    const val EMAILJS_FORM_URL = "https://api.emailjs.com/api/v1.0/email/send-form"
    const val GITHUB_GRAPHQL_URL = "https://api.github.com/graphql"
}