package com.pat.portfolio.core.constants

object Icons {
    private const val BASE_ICON_PATH = "/icons"

    // Code
    const val ANGULAR_ICON = "$BASE_ICON_PATH/code/angular.svg"
    const val BICEP_ICON = "$BASE_ICON_PATH/code/bicep.svg"
    const val CSHARP_ICON = "$BASE_ICON_PATH/code/c-sharp.svg"
    const val KOTLIN_ICON = "$BASE_ICON_PATH/code/kotlin-icon.svg"
    const val KOBWEB_ICON = "$BASE_ICON_PATH/code/kobweb.webp"
    const val COMPOSE_HTML_ICON = "$BASE_ICON_PATH/code/compose-multiplatform.svg"
    const val CSS_ICON = "$BASE_ICON_PATH/code/css.svg"
    const val DART_ICON = "$BASE_ICON_PATH/code/dart.svg"
    const val DOTNET_ICON = "$BASE_ICON_PATH/code/dotnet.svg"
    const val FLUTTER_ICON = "$BASE_ICON_PATH/code/flutter.svg"
    const val FRAMER_ICON = "$BASE_ICON_PATH/code/framer.svg"
    const val GREENSOCK_ICON = "$BASE_ICON_PATH/code/greensock-icon.svg"
    const val HTML_ICON = "$BASE_ICON_PATH/code/html.svg"
    const val JAVASCRIPT_ICON = "$BASE_ICON_PATH/code/javascript.svg"
    const val JQUERY_ICON = "$BASE_ICON_PATH/code/jquery.svg"
    const val JSON_ICON = "$BASE_ICON_PATH/code/json.svg"
    const val LIQUID_ICON = "$BASE_ICON_PATH/code/liquid.svg"
    const val NEXT_JS_ICON = "$BASE_ICON_PATH/code/nextjs-icon.svg"
    const val NODEJS_ICON = "$BASE_ICON_PATH/code/nodejs.svg"
    const val PHP_ICON = "$BASE_ICON_PATH/code/php.svg"
    const val POWERSHELL_ICON = "$BASE_ICON_PATH/code/powershell.svg"
    const val REACT_ICON = "$BASE_ICON_PATH/code/react.svg"
    const val REDUX_ICON = "$BASE_ICON_PATH/code/redux.svg"
    const val SQL_ICON = "$BASE_ICON_PATH/code/sql.svg"
    const val TYPESCRIPT_ICON = "$BASE_ICON_PATH/code/typescript-icon.svg"
    const val XML_ICON = "$BASE_ICON_PATH/code/xml.svg"
    const val XSLT_ICON = "$BASE_ICON_PATH/code/xslt.svg"
    const val YAML_ICON = "$BASE_ICON_PATH/code/yaml.svg"

    // Tools
    const val AFFINITY_DESIGNER_ICON = "$BASE_ICON_PATH/tools/affinity-designer.svg"
    const val ANDROID_STUDIO_ICON = "$BASE_ICON_PATH/tools/android-studio.svg"
    const val AZ_CLI_ICON = "$BASE_ICON_PATH/tools/azcli.svg"
    const val AZURE_DEVOPS_ICON = "$BASE_ICON_PATH/tools/azdevops.svg"
    const val AZURE_ICON = "$BASE_ICON_PATH/tools/azure.svg"
    const val AZURE_POWERSHELL_ICON = "$BASE_ICON_PATH/tools/azpowershell.svg"
    const val CONFLUENCE_ICON = "$BASE_ICON_PATH/tools/confluence.svg"
    const val COSMOSDB_ICON = "$BASE_ICON_PATH/tools/cosmosdb.svg"
    const val FHIR_ICON = "$BASE_ICON_PATH/tools/fhir.svg"
    const val FIGMA_ICON = "$BASE_ICON_PATH/tools/figma.svg"
    const val GIT_ICON = "$BASE_ICON_PATH/tools/git.svg"
    const val ADMOB_ICON = "$BASE_ICON_PATH/tools/google-admob.svg"
    const val GOOGLE_CLOUD_ICON = "$BASE_ICON_PATH/tools/google-cloud.svg"
    const val INTELLIJ_ICON = "$BASE_ICON_PATH/tools/intellij-idea.svg"
    const val MARIADB_ICON = "$BASE_ICON_PATH/tools/mariadb.svg"
    const val MATRIX_ICON = "$BASE_ICON_PATH/tools/matrix.svg"
    const val MSSQL_ICON = "$BASE_ICON_PATH/tools/mssql.svg"
    const val MS_SUITE_ICON = "$BASE_ICON_PATH/tools/mssuite.svg"
    const val NOTION_ICON = "$BASE_ICON_PATH/tools/notion.svg"
    const val PHPSTORM_ICON = "$BASE_ICON_PATH/tools/phpstorm.svg"
    const val VERCEL_ICON = "$BASE_ICON_PATH/tools/vercel.svg"
    const val VS_CODE_ICON = "$BASE_ICON_PATH/tools/visual-studio-code.svg"
    const val VS_ICON = "$BASE_ICON_PATH/tools/vs.svg"

    // Social platforms
    const val LINKEDIN_ICON = "$BASE_ICON_PATH/social/linkedin-icon.svg"
    const val GITHUB_ICON = "$BASE_ICON_PATH/social/github-icon.svg"

    // General icons
    const val PORTFOLIO_V1_ICON = "$BASE_ICON_PATH/web/portfolio-v1.svg"
    const val PORTFOLIO_V2_ICON = "$BASE_ICON_PATH/web/Icon.svg"
}